### ISSUE TITLE
Folder structure & best practices

### ISSUE THREAD

**Issue by MattZK** [AP-Elektronica-ICT/jp19-lafa#14]
Define a project folder structure & best practices for that stucture.
Also discuss repo-wide language.

**Comment by MattZK** [comment]
Also resolve open requests #10 & #11

**Comment by MattZK** [comment]
Source
- src/sensors
- src/atmega
- src/webserver (docker-compose)
- src/dashboard (RPi Touch -- Later Stage)
- src/node-master
- src/cluster-master
Hardware
- hdw/PCB (Design Files, Multisim...)
- hdw/CAD

**Comment by MattZK** [comment]
Main Language: English
Branch Name: {
  Global: Full Lowercase
  Feature Branch: feature-<issue_number_github> bv "feature-17"
  Fix/Bug Branch: bug-<issue_number_github> 
  Refactor Branch: refactor-<issue_number_github>
}

**Comment by MattZK** [comment]
Add to readme

**Comment by MattZK** [comment]
### Main Language: EN
### Branches:
- Feature Branch: feature-<JIRA_story_number>-keyword (eg. _feature-40-mqtt_ for JP19LAFA-40 As a developer, I want sensor updates to happen using MQTT)
- Fix/Bug Branch: bug-<github_issue_number>
- Refactor Branch: refactor-<github_issue_number>

### Merges:
- SQUASH MERGE ONLY!
- ONE FEATURE is ONE COMMIT on master!
- Title: Short Description (<github_pull_request_number>)
- Description: Precise description of the changes

**Comment by MattZK** [comment]
## Folder Structure
### Source Files
#### Sensors
`src/sensors/<sensor_type>`
-> program -- contains programmed content (main program should be called main)
-> files -- contains all other files related to this sensor (3D, electrical, ...)
#### Actuators
`src/actuators/<actuator_type>`
-> program -- contains programmed content (main program should be called main)
-> files -- contains all other files related to this actuator (3D, electrical, ...)
#### Controllers / Global PCB's
`src/controllers/<controller_type>`
-> program -- contains programmed content (should be broken down in to multiple folders if contains multiple controllers code)
-> files -- contains all other files related to this controller (3D, electrical, ...)
#### Web Platform (Server)
`src/server/<sensor_type>`
TO BE DEFINED

**Comment by F0xedb** [comment]
## Issue Structure

### Feature
* Title: [FEATURE] **user store number** -**keyword** (eg. [FEATURE] 41-light)

### BUG
* Title: [BUG] feature-**user store number** -**keyword** (eg. [BUG] feature-41-light)

### REFACTOR
* Title: [REFACTOR] feature-**user store number**-**keyword** (eg. [REFACTOR] feature-41-light)
* Title: [REFACTOR]  global-**keyword** (eg. [REFACTOR] global-CamelCase)
* Title: [REFACTOR]  featurelist-**story 1, story 2, ..., story N**-**keyword** (eg. [REFACTOR] featurelist-41, 11, 8) I²C callback format fixed

**Comment by F0xedb** [comment]
We have migrated to a new organization. This repo is no longer valid.
See https://github.com/jp19-lafa for more info
