### ISSUE TITLE
Feedback Analyse

### ISSUE THREAD

**Issue by luytsm** [AP-Elektronica-ICT/jp19-lafa#23]
# Analyse 
Uitgebreide analyse ++

- [x]  Alles gebeurt over een HTTP dmv een API, zie ook eens een keer naar MQTT (Dit zal eenvoudiger te 
       schalen zijn)
- [x] In de hardware analyse word er ook nergens gesproken over energie. Hoe gaan we de opstelling van 
       een schaalbare  energie bron voorzien wat zijn de vereisten
- [x] Een Raspberry Pi als host voor de web en database kan werken, maar dit gaat niet echt schaalbaar zijn. We hebben via het school credits voor het GCP. Bezie deze optie ook, bezie ook enkele SaaS en IaaS service omtrent IoT (bv IoT Hub Azure) 

# Jira
- [x] Niet iedereen heeft een actieve stort op Jira
- [ ] Release planning 
- [ ] Criteria of Done

**Comment by MattZK** [comment]
Compliance Issues:
- #24 MQTT & API
- #25 Energy
- #26 Jira

**Comment by MattZK** [comment]
Progress:
- MQTT has been implemented
- Cloud server acts as MQTT Broker & Cloud Dashboard (mqtt.farmlab.team:1883 & cloud.farmlab.team)
