### ISSUE TITLE
[FEATURE] 41-Movable camera

### ISSUE THREAD

**Issue by BMatrix** [AP-Elektronica-ICT/jp19-lafa#39]
**Feature description**
As it would be impractical to use a camera for each plant. As single camera will be used for each row. To make sure that it is ablt to see every plant it has to be able to move above the plants on a rail, or similar.

**Solution**
The camera will be mounted on above tha plants. They will be able to be moved via a pulley and belt attached to a stepper motor. This stepper motor will be driven by a driver that is controlled by the Raspberry Pi 

**Additional context**
See jira for complete user story [user story](https://jira.ap.be/browse/JP19LAFA-41)

**Comment by F0xedb** [comment]
We have migrated to a new organization. This repo is no longer valid.
See https://github.com/jp19-lafa for more info
