### ISSUE TITLE
[FEATURE] 13-dashboard

### ISSUE THREAD

**Issue by MattZK** [AP-Elektronica-ICT/jp19-lafa#63]
**Jira ID**
JP19LAFA-13

**Feature description**
A user dashboard to control every node both locally and remotely. This should be accessible from cloud.farmlab.team. This should be dockerized as well. Initial feature does not require user authentication.

**Context**
See jira for complete user story [user story](https://jira.ap.be/browse/JP19LAFA-13)

**Comment by F0xedb** [comment]
We have migrated to a new organization. This repo is no longer valid.
See https://github.com/jp19-lafa for more info
