### ISSUE TITLE
Add a Node Diagram

### ISSUE THREAD

**Issue by MattZK** [AP-Elektronica-ICT/jp19-lafa#7]
Add a diagram showing scalability of nodes using a master node (analysis/README.md)

**Comment by F0xedb** [comment]
Issue is resolved! Added both a scalable/reliable network of nodes (if a node goes down then everything still works) and a unreliable network. 
Note: in the scalable version we need switches with at least 5 ports.
In the version that is unreliable we need switches with at least 4 ports.
